# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/ (optional)
url: "http://heatherlucas.net" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Heather Lucas # Your name will go here
  description: "A personal portfolio and blog website" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Web Developer and Changemaker</h1>
     <p>Determined to make the world better through code, one byte at a time.</p>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a>.
  # Icons
  rss: false
  email_address: hlucas@gmail.com
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  github: hlucas217
  google_plus: 
  instagram: 
  linkedin:  https://www.linkedin.com/in/heather-schall-lucas-8531a94a
  pinterest: 
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: meowveg
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-91030955-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lato:300,400,700,300italic,700italic|Abril+Fatface"

# PAGINATION
paginate: 100
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# BUILD SETTINGS
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
